[workspace]
types = "packages/types"

[features]
seeds = false
skip-lint = false
[programs.devnet]
treasury_controller = "stcGmoLCBsr2KSu2vvcSuqMiEZx36F32ySUtCXjab5B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "packages/tests/fixtures/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/*.ts"
register_state = "yarn run ts-node packages/scripts/registerState.ts"
get_state = "yarn run ts-node packages/scripts/getState.ts"
update_state = "yarn run ts-node packages/scripts/updateState.ts"
allocate_yield = "yarn run ts-node packages/scripts/allocateYield.ts"
set_delegate = "yarn run ts-node packages/scripts/setDelegate.ts"
